### ISSUE TITLE
Add more specific documentation

### ISSUE THREAD

**Issue by omnone** [omnone/openweatherWidget#6]
Currently documentation is poor, it would be nice to add how to build and run the project and also how to build an executable for Windows, Linux etc. based on the build scripts. Also , it needs more information for how to set the parameters on main.js in order to correspond to the users location , timezone etc.

**Comment by prashant314** [comment]
Hello  @omnone can I pick this issue?

**Comment by prashant314** [comment]
Hello @omnone when I try to run the project it is giving me an error at line:90 in main.js. Please suggest where am I going wrong. Thanks!
![image](https://user-images.githubusercontent.com/48221944/95302693-e9302180-089f-11eb-9889-cd5883f83d6d.png)

**Comment by omnone** [comment]
Hey , what error does it give you?

**Comment by prashant314** [comment]
![image](https://user-images.githubusercontent.com/48221944/95306328-e552ce00-08a4-11eb-9116-9dae0b72c43e.png)

**Comment by omnone** [comment]
Have you installed all the dependencies? Also you need to set the environment variables accordingly such as getting an api key for openweather , google  calendar etc.

**Comment by prashant314** [comment]
Yes @omnone I had installed all the dependencies. But the environment variable file might be the issue. As you have added it now, I wanted to know whether only these 2 variables(city name & openweather api key) are only needed or is there any other requirement also? As I had seen a token.json reference somewhere in the code but this file is also missing here. Please suggest
